### ISSUE TITLE
Remove dependency on Newtonsoft.Json

### ISSUE THREAD

**Issue by jasonmitchell** [sequin/sequin#34]
Possibly swap to use a smaller library like Jil?

**Comment by JoeStead** [comment]
+1

**Comment by JoeStead** [comment]
I'm not sure if this is a great idea. Jil seems to struggle with objects that don't have a default constructor, where as Newtonsoft.Json doesn't (even if it is a bit heavyweight). It seems a little imposing to force people to either have setters + a default constructor on their commands, or do some hokey-pokey magic stuff.

**Comment by jasonmitchell** [comment]
I wouldn't really want to lose the ability to deserialise using constructors.  So perhaps Newtonsoft.Json is a bit heavier than what Sequin needs but it does have benefits.  Happy to close this if we don't feel like it's necessary.

**Comment by JoeStead** [comment]
I need to look into this more tomorrow, it was really annoying me earlier in the day. I'll read up to see if there is a non-forceful workaround.
