### ISSUE TITLE
Add support for ASP.NET Core 1.0 

### ISSUE THREAD

**Issue by JoeStead** [sequin/sequin#37]
The current implementation is using katana, which is cool, moving forward it may be worth adding support for the ASP.NET Core 1.0 (OR WHATEVER THE HELL IT IS CALLED THIS WEEK) pipeline. 

This could potentially be extended to add support for .NET core.

(This would be a breaking change, so may be a different project with a lot of duplicate code)

**Comment by JoeStead** [comment]
Now I've got a copy of Rider, this is something I'm seriously gonna look into as a little side project. Obviously version 1 should support ASP.NET old/normal/idk what to call this.

 How do you want to handle it @jasonmitchell, obviously I'll work in my fork, but at some point it would be nice to merge it (if you want this of course)?

**Comment by jasonmitchell** [comment]
Yes this is definitely wanted post-version 1.  Just fork it and have a go.

**Comment by JoeStead** [comment]
This should be simpler now things have RTM'd and the refactoring away from the Microsoft.Owin dependency

**Comment by JoeStead** [comment]
lmao.
