### ISSUE TITLE
Provide in JsonConvert options

### ISSUE THREAD

**Issue by JoeStead** [sequin/sequin#44]
Consider the following command:

```csharp
public class RegisterUser
{
    public Guid Id { get; set; }
    public string FirstName { get; set; }
}
```

and consider the following request: 
```json
{
     "firstName": "joe",
}
```

You'd expect it to come back with some validation errors (provided you've setup validators properly) around the Id being required.

Currently the serializer throws an exception instead. This **might** happen for other value types too, I'm not sure. 

The choices I have to fix this: 

1. Making the `Id` property in my command nullable, which kind of bleeds out into the entire application (and it isn't actually nullable, so I shouldn't do this).
2. Tell the serialiser that it should use a Guid.Empty if it is null rather than throwing an exception by using a [Custom Converter](http://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm). 
    - This comes with the full buy in to JSON.NET if we expose an API to add converters. 

Thoughts @jasonmitchell?

**Comment by jasonmitchell** [comment]
Let's go with option 2 and just make use of JSON.NET.  This means we can close #34
