### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by jasonmitchell** [sequin/sequin#46]
It's a massive pain at the minute to make changes across multiple projects as the dependencies on this like the core project are a massive pain in the ass.

**Comment by jasonmitchell** [comment]
This should be somewhat reduced due to the Sequin.Owin changes and removal of the dependency on Sequin.Core.

**Comment by JoeStead** [comment]
Have you fixed this yet?

**Comment by jasonmitchell** [comment]
Maybe
